PhotoContest.Web/Models/ContestViewModel.cs
using PhotoContest.Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Web.Models
{
    public class ContestViewModel
    {
        //public ContestViewModel(Contest contest)
        //{
        //    this.Title = contest.Title;
        //    this.Category = contest.Category;
        //}

        public string Title { get; set; }
        public string Category { get; set; }
    }
}

PhotoContest.Web/Controllers/PictureController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PhotoContest.Common.Helpers;
using PhotoContest.Models.DTOs;
using PhotoContest.Models.Models;
using PhotoContest.Service;
using PhotoContest.Service.Contracts;
using PhotoContest.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Web.Controllers
{
    public class PictureController : Controller
    {
        private readonly IPictureService _pictureService;
        private readonly IWebHostEnvironment _webHostEnvironment; 
        private readonly AuthorisationHelper _authHelper;

        public PictureController(IPictureService pictureService, IWebHostEnvironment webHostEnvironment, AuthorisationHelper authHelper)
        {
            this._pictureService = pictureService;
            _webHostEnvironment = webHostEnvironment;
            _authHelper = authHelper;
        }
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult UploadPicture(int id)
        {
            var viewModel = new PictureViewModel
            {
                ContestId = id
            };
            return View(model:viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadPicture(PictureViewModel viewModel, int id)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadModel(viewModel);
                string username = TempData["username"].ToString();
                TempData.Keep();
                User author = this._authHelper.TryGetUser(username);
                bool isUserPictures = this._pictureService.IsUserPictures(id, username);

                if (!isUserPictures)
                {
                    PictureDTO pictureDTO = new PictureDTO
                    {
                        Title = viewModel.Title,
                        Story = viewModel.Story,
                        CreatedOn = DateTime.Now,
                        AuthorId = author.Id,
                        ImageFile = uniqueFileName,
                        ContestId = id,
                    };
                    await this._pictureService.Insert(pictureDTO);
                }
                else this.HttpContext.Session.SetString("SecondPhoto", string.Empty);

            }


            return RedirectToAction(actionName: "Index", controllerName: "Contests");
        }
        [HttpPost]
        public async Task<IActionResult> VotePicture(int id, VotePictureModel voteModel)
        {
            var picture = this._pictureService.GetPictureById(id);
            string username = TempData["username"].ToString();
            TempData.Keep();
            User author = this._authHelper.TryGetUser(username);
            var voteDTO = new VoteDTO
            {
                PictureId = id,
                UserId = author.Id,
                ContestId = picture.ContestId,
                Comment = voteModel.Comment,
                Rating = voteModel.Rating,
            };
            await this._pictureService.Vote(voteDTO);
            return RedirectToAction(actionName: "Vote", controllerName: "Contests", new { @id = picture.ContestId });
        }
        [HttpPost]
        public async Task<IActionResult> WrongCategory(int id)
        {
            var picture = this._pictureService.GetPictureById(id);
            string username = TempData["username"].ToString();
            TempData.Keep();
            User author = this._authHelper.TryGetUser(username);
            var voteDTO = new VoteDTO
            {
                PictureId = id,
                UserId = author.Id,
                ContestId = picture.ContestId,
                Comment = "Wrong category!",
                Rating = 0,
            };
            await this._pictureService.Vote(voteDTO);
            return RedirectToAction(actionName: "Vote", controllerName: "Contests", new { @id = picture.ContestId });
        }
        private string UploadModel(PictureViewModel viewModel)
        {
            string uniqueFileName = null;
            if (viewModel.ImageFile != null)
            {
                string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + viewModel.ImageFile.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    viewModel.ImageFile.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}


//if (pictureViewModel.ImageFile != null)
//{

//    string username = TempData["username"].ToString();
//    //string contestTitle = TempData["contestTitle"].ToString();
//    //convert image to string and send to database
//    string contestTitle = pictureViewModel.ContestTitle;
//    string pictureTitle = pictureViewModel.Title;
//    string pictureStory = pictureViewModel.Story;
//    using (MemoryStream ms = new MemoryStream())
//    {
//        pictureViewModel.ImageFile.CopyTo(ms);
//        byte[] fileBytes = ms.ToArray();
//        string convertedPhoto = Convert.ToBase64String(fileBytes);

//        this.pictureService.Insert(convertedPhoto, username, contestTitle, pictureTitle, pictureStory);
//    }

//}

PhotoContest.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using PhotoContest.Common.Exceptions;
using PhotoContest.Common.Helpers;
using PhotoContest.Models.DTOMapper;
using PhotoContest.Models.DTOs;
using PhotoContest.Models.DTOs.ListModels;
using PhotoContest.Models.Models;
using PhotoContest.Service.Contracts;
using PhotoContest.Web.Models;
using PhotoContest.Web.Models.ViewModelMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly AuthorisationHelper _authorisationHelper;
        private readonly IUserService _userService;
        private readonly IContestService _contestService;

        public UserController(AuthorisationHelper authorisationHelper, IUserService userService, IContestService contestService)
        {
            this._authorisationHelper = authorisationHelper;
            this._userService = userService;
            this._contestService = contestService;
        }

        public IActionResult GetUsers()
        {
            IEnumerable<UserDTO> users = this._userService.GetAllUsers();
            var userList = new UserIndex
            {
                UserList = users
            };
            return this.View(model: userList);
        }
        public IActionResult LoginUser()
        {
            var viewModel = new LoginViewModel();
            return this.View(model: viewModel);
        }

        [HttpPost]
        public IActionResult LoginUser(LoginViewModel viewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model: viewModel);
            }
            try
            {
                var user = this._authorisationHelper.TryGetUser(viewModel.Username, viewModel.Password);
                var userDTO = user.GetDTO();

                this.HttpContext.Session.SetString("CurrentUser", user.Username);

                TempData["username"] = viewModel.Username;
                TempData.Keep();

                if (user.IsOrganizer == true)
                {
                    this.HttpContext.Session.SetString("IsOrganiser", string.Empty);
                }
                if (user.RoleId == 1 || user.IsPhotoJunkey == true)
                {
                    this.HttpContext.Session.SetString("IsPhotoJunkey", string.Empty);
                }

                return this.RedirectToAction(actionName: "Index", controllerName: "Home");
            }
            catch (AuthenticationException)
            {
                //this.ModelState.AddModelError("Username", e.Message);
                this.ModelState.AddModelError("Password", "Invalid credentials!");
                return this.View(model: viewModel);
            }
            catch (ArgumentException)
            {
                this.ModelState.AddModelError("Password", "Invalid credentials!");
                return this.View(model: viewModel);
            }
        }

        public IActionResult Logout()
        {
            this.HttpContext.Session.Remove("CurrentUser");
            this.HttpContext.Session.Clear();
            return RedirectToAction(actionName: "Index", controllerName: "Home");
        }

        public IActionResult Register()
        {
            var viewModel = new RegisterViewModel();
            return this.View(model: viewModel);
        }
        [HttpPost]
        public IActionResult Register(RegisterViewModel viewModel)
        {

            if (!this.ModelState.IsValid)
            {
                return this.View(model: viewModel);
            }
            if (this._userService.Exist(viewModel.Username))
            {
                this.ModelState.AddModelError("Username", "User with same username already exists.");
                return this.View(model: viewModel);
            }
            if (viewModel.Password != viewModel.ConfirmPassword)
            {
                this.ModelState.AddModelError("ConfirmPassword", "The password and confirmation password do not match.");
                return this.View(model: viewModel);
            }

            User user = viewModel.GetUser();
            this._userService.InsertUser(user);

            return this.RedirectToAction(actionName: "Index", controllerName: "Home");
        }
        public IActionResult Details()
        {
            //var user = this._userService.GetUser(id);
            string username = TempData["username"].ToString();
            TempData.Keep();
            var user = this._authorisationHelper.TryGetUser(username);
            var viewModel = new UserViewModel
            {
                Username = user.Username,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Score = user.Score,
                CreatedOn = user.CreatedOn,
                OpenContests =  this._contestService.UserOpenedContests(user.Username),
                ContestsInVotePhase =  this._contestService.UserVotingContests(user.Username),
                FinishedContests =  this._contestService.UserFinishedContests(user.Username),
            };
            return this.View(model: viewModel);
            //var userDto = user.GetDTO();
            //return this.View(model: userDto);
        }
        public IActionResult AuthorDetails(int id)
        {
            var user = this._userService.GetUser(id);
            var viewModel = new UserViewModel
            {
                Username = user.Username,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Score = user.Score,
                CreatedOn = user.CreatedOn,
                OpenContests =  this._contestService.UserOpenedContests(user.Username),
                ContestsInVotePhase =  this._contestService.UserVotingContests(user.Username),
                FinishedContests =  this._contestService.UserFinishedContests(user.Username),
            };
            return this.View(model: viewModel);
        }

        public IActionResult DetailsUser(int id)
        {
            var user = this._userService.GetUser(id);
            var viewModel = new UserViewModel
            {
                Username = user.Username,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Score = user.Score,
                CreatedOn = user.CreatedOn,
                OpenContests = this._contestService.UserOpenedContests(user.Username),
                ContestsInVotePhase = this._contestService.UserVotingContests(user.Username),
                FinishedContests = this._contestService.UserFinishedContests(user.Username),
            };
            return this.View(model: viewModel);
        }
        public IActionResult FinishedContest()
        {
            string username = TempData["username"].ToString();
            TempData.Keep();
            var finished =  this._contestService.UserFinishedContests(username);
            var contests = new ContestIndex
            {
                ContestList = finished
            };
            return this.View(model: contests);
        }
        public IActionResult VoteContests()
        {
            string username = TempData["username"].ToString();
            TempData.Keep();
            var finished =  this._contestService.UserVotingContests(username);
            var contests = new ContestIndex
            {
                ContestList = finished
            };
            return this.View(model: contests);
        }
        public IActionResult OpenContests()
        {
            string username = TempData["username"].ToString();
            TempData.Keep();
            var finished =  this._contestService.UserOpenedContests(username);
            var contests = new ContestIndex
            {
                ContestList = finished
            };
            return this.View(model: contests);
        }
    }
}

PhotoContest.Web/Views/Contests/ClosedUserContests.cshtml
@{
    this.ViewData["Title"] = "ClosedUserContest";
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["IsOrganiser"] = this.Context.Session.Keys.Contains("IsOrganiser");
    int count = 1;
}
<body>

    <table class="table table-hover table-striped">
        <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Contest Title</th>
                <th scope="col">Second phase end</th>
                <th scope="col">Contest Category</th>
            </tr>
        </thead>

        @model PhotoContest.Models.DTOs.ListModels.ContestIndex
        <tbody class="table-hover">
            @if (Model.ContestList.Any())
            {
                @foreach (var contest in Model.ContestList)
                {
                    <tr>
                        <td>
                            @count
                        </td>
                        <td>
                            <a asp-controller="Contests" asp-action="Details" asp-route-id="@contest.Id">
                                @contest.Title
                            </a>
                        </td>
                        <td>
                            @contest.DueDate.ToString("HH:mm dd-MMMM/yyyy")
                        </td>
                        <td>
                            @contest.ContestType
                        </td>
                    </tr>
                    count++;
                }
            }
        </tbody>
    </table>
</body>

PhotoContest.Web/Views/Contests/Details.cshtml
@{
    this.ViewData["Title"] = "OpenContests";
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["IsPhotoJunkey"] = this.Context.Session.Keys.Contains("IsPhotoJunkey");
    this.ViewData["SecondPhoto"] = this.Context.Session.Keys.Contains("SecondPhoto");
    @using PhotoContest.Models.Models.eNums;

}
@model PhotoContest.Models.DTOs.ContestDTO

<body>
    <div>

        @if ((bool)this.ViewData["IsAuthenticated"])
        {

            @if ((bool)this.ViewData["IsPhotoJunkey"])
            {
                if (Model.Phase == Phase.Open)
                {
                    if (!Model.IsUserContest)
                    {
                        <div class="form-group">
                            <p>
                                <a asp-controller="Picture" asp-action="UploadPicture" class="btn btn-secondary" asp-route-id="@Model.Id">
                                    <span>Enroll</span>
                                </a>
                            </p>
                        </div>
                    }
                }
            }
        }
    </div>

    <div style="color: cornsilk;">
        <h3>
            @Model.Title
        </h3>
        @if (Model.Pictures.Any())
        {
            var Pictures = Model.Pictures.ToArray();
            for (int i = 0; i < Pictures.Length; i++)
            {

                var picture = Pictures[i];

                <div class="container" style="max-width: 470px; max-height:420px; display: inline-block; padding: 20px;">


                    <div class="card">
                        <img src="~/Uploads/@picture.ImageFile" class="card-img-top">
                        <div class="card-body" style="color: black;">
                            <h5 class="card-title">@picture.Title</h5>
                            <p class="card-text">@picture.Story</p>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-success" style=" margin-left: 85px; padding-left: 60px; padding-right: 60px; margin-right: 20px;"
                                    href="#" data-toggle="modal" data-target="#myDetailsModal-@i">
                                Show more...
                            </button>

                        </div>
                        <div class="modal fade" style="color:GrayText" id="myDetailsModal-@i">
                            <div class="modal-dialog modal-lg modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1>@picture.Title</h1>
                                    </div>
                                    <div class="modal-body">
                                        <img src="~/Uploads/@picture.ImageFile" style="width:765px;">
                                        <div class="modal-footer">
                                            <b>
                                                <i>
                                                    @picture.Story

                                                </i>
                                            </b>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button class="btn btn-danger" data-toggle="modal" data-target="#myDetailsModal-@i">
                                            Close
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            }
        }
    </div>

</body>

PhotoContest.Web/Views/Contests/DetailsRated.cshtml
@{
    this.ViewData["Title"] = "DetailsRated";
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["IsPhotoJunkey"] = this.Context.Session.Keys.Contains("IsPhotoJunkey");
    @using PhotoContest.Models.Models.eNums;
    bool sharedFirst = false;
    bool sharedSecond = false;
    bool sharedThird = false;
}
@model PhotoContest.Models.DTOs.ContestDTO
<body>
    <div style="color: cornsilk;">
        <h3>
            @Model.Title
        </h3>
        @if (Model.Pictures.Any())
        {
            var pictures = Model.Pictures.ToArray();

            var PicturesWinners = pictures.OrderByDescending(p => p.Rating).ToArray();
            for (int i = 0; i < PicturesWinners.Count(); i++)
            {

                var picture = PicturesWinners[i];

                <div class="container" style="max-width: 470px; max-height: 420px; display: inline-table; padding: 20px;">


                    @if (i == 0 && i + 1 < pictures.Count())
                    {
                        if (pictures[i].Rating == pictures[i + 1].Rating)
                        {
                            sharedFirst = true;
                        }
                        if (pictures[i].Rating > pictures[i + 1].Rating)
                        {
                            sharedFirst = false;
                        }
                    }
                    @if (i == 1 && sharedFirst == false && i + 1 < pictures.Count())
                    {
                        if (pictures[i].Rating == pictures[i + 1].Rating)
                        {
                            sharedSecond = true;
                        }
                        if (pictures[i].Rating > pictures[i + 1].Rating)
                        {
                            sharedSecond = false;
                        }
                    }
                    @if (i == 2 && sharedFirst == true && i + 1 < pictures.Count())
                    {
                        if (pictures[i].Rating == pictures[i + 1].Rating)
                        {
                            sharedSecond = true;
                        }
                        if (pictures[i].Rating > pictures[i + 1].Rating)
                        {
                            sharedSecond = false;
                        }
                    }
                    @if (i == 2 && sharedFirst == false && sharedSecond == false && i + 1 < pictures.Count())
                    {
                        if (pictures[i].Rating == pictures[i + 1].Rating)
                        {
                            sharedThird = true;
                        }
                        if (pictures[i].Rating > pictures[i + 1].Rating)
                        {
                            sharedThird = false;
                        }
                    }
                    @if (i == 3 && sharedFirst == true && sharedSecond == false && i + 1 < pictures.Count())
                    {
                        if (pictures[i].Rating == pictures[i + 1].Rating)
                        {
                            sharedThird = true;
                        }
                        if (pictures[i].Rating > pictures[i + 1].Rating)
                        {
                            sharedThird = false;
                        }
                    }
                    @if (i == 3 && sharedFirst == false && sharedSecond == true && i + 1 < pictures.Count())
                    {
                        if (pictures[i].Rating == pictures[i + 1].Rating)
                        {
                            sharedThird = true;
                        }
                        if (pictures[i].Rating > pictures[i + 1].Rating)
                        {
                            sharedThird = false;
                        }
                    }
                    @if (i == 4 && sharedFirst == true && sharedSecond == true && i + 1 < pictures.Count())
                    {
                        if (pictures[i].Rating == pictures[i + 1].Rating)
                        {
                            sharedThird = true;
                        }
                        if (pictures[i].Rating > pictures[i + 1].Rating)
                        {
                            sharedThird = false;
                        }
                    }
                    <div class="card">
                        @if (i == 0 && sharedFirst == false)
                        {
                            <div class="card-header" style="color:goldenrod;">First place</div>
                        }
                        @if (i < 2 && sharedFirst == true)
                        {
                            <div class="card-header" style="color:goldenrod;">First place</div>
                        }
                        @if (i == 1 && sharedFirst == false && sharedSecond == false)
                        {
                            <div class="card-header" style="color:goldenrod;"> Second place</div>
                        }
                        @if ((i == 2 || i == 3) && sharedFirst == true && sharedSecond == true)
                        {
                            <div class="card-header" style="color:goldenrod;"> Second place</div>
                        }
                        @if ((i == 1 || i == 2) && sharedSecond == true && sharedFirst == false)
                        {
                            <div class="card-header" style="color:goldenrod;"> Second place</div>
                        }
                        @if (i == 2 && sharedFirst == false && sharedSecond == false)
                        {
                            <div class="card-header" style="color:goldenrod;">Third place</div>
                        }
                        @if (i == 3 && sharedFirst == true || sharedSecond == true)
                        {
                            <div class="card-header" style="color:goldenrod;">Third place</div>
                        }
                        @if (i == 4 && sharedFirst == true && sharedSecond == true && sharedThird == false)
                        {
                            <div class="card-header" style="color:goldenrod;">Third place</div>
                        }
                        @if (i > 3 && i < 6 && sharedFirst && sharedSecond == true && sharedThird == true)
                        {
                            <div class="card-header" style="color:goldenrod;">Third place</div>
                        }

                        <img src="~/Uploads/@picture.ImageFile" class="card-img-top">
                        <div class="card-body" style="color: black;">
                            <h5 class="card-title">@picture.Title</h5>
                            <div class="card-footer">
                            <p class="card-text">@picture.Story</p>
                            <p class="card-text">@picture.Rating </p>

                            </div>
                            <div class="card-footer">
                                <p class="card-text">@picture.Author.FirstName @picture.Author.LastName</p>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-success" style=" margin-left: 85px; padding-left: 60px; padding-right: 60px; margin-right: 20px;"
                                    href="#" data-toggle="modal" data-target="#myDetailsModal-@i">
                                Show more...
                            </button>

                        </div>
                        <div class="modal fade" style="color:GrayText" id="myDetailsModal-@i">
                            <div class="modal-dialog modal-lg modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1>@picture.Title</h1>
                                    </div>
                                    <div class="modal-body">
                                        <img src="~/Uploads/@picture.ImageFile" style="width:765px;">
                                        <div class="modal-footer">
                                            <b>
                                                <i>
                                                    @picture.Story

                                                </i>
                                            </b>
                                        </div>
                                        <div class="modal-footer">
                                            <a asp-action="AuthorDetails" asp-controller="User" asp-route-id="@picture.Author.Id">@picture.Author.Username</a>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button class="btn btn-danger" data-toggle="modal" data-target="#myDetailsModal-@i">
                                            Close
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            }
        }
    </div>

</body>

PhotoContest.Web/Views/Contests/FinishedContests.cshtml
@{
    this.ViewData["Title"] = "FinishedContests";
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["IsOrganiser"] = this.Context.Session.Keys.Contains("IsOrganiser");
    int count = 1;
}
<body>

    <table class="table table-hover table-striped">
        <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Contest Title</th>
                <th scope="col">Finished on</th>
                <th scope="col">Contest Category</th>
            </tr>
        </thead>

        @model PhotoContest.Models.DTOs.ListModels.ContestIndex
        <tbody class="table-hover" style="background-color: gainsboro">
            @if (Model.ContestList.Any())
            {
                @foreach (var contest in Model.ContestList)
                {
                    <tr>
                        <td>
                            @count
                        </td>
                        <td>
                            <a asp-controller="Contests" asp-action="Details" asp-route-id="@contest.Id">
                                @contest.Title
                            </a>
                        </td>
                        <td>
                            @contest.DueDate.ToString("HH:mm dd-MMMM/yyyy")
                        </td>
                        <td>
                            @contest.ContestType
                        </td>
                    </tr>
                    count++;
                }
            }
        </tbody>
    </table>
</body>